"""cleared unique true

Revision ID: 9e897f2fb99a
Revises: da70a6df8a83
Create Date: 2026-02-21 15:00:18.615753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e897f2fb99a'
down_revision: Union[str, Sequence[str], None] = 'da70a6df8a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workers_name_key'), 'workers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('workers_name_key'), 'workers', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
